/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assinaturas;


import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gustavo.lima
 */
public class TelaDois extends javax.swing.JFrame {

    /**
     * Creates new form TelaDois
     */
    public TelaDois() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nomeLabelRu1 = new javax.swing.JLabel();
        areaLabelRu1 = new javax.swing.JLabel();
        siteLabelRU = new javax.swing.JLabel();
        zapLabelRU = new javax.swing.JLabel();
        emailLabelRU = new javax.swing.JLabel();
        telefoneLabelRU = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        ramalTextField = new javax.swing.JTextField();
        areaTextField = new javax.swing.JTextField();
        Zap = new javax.swing.JLabel();
        zapFormattedTextField = new javax.swing.JFormattedTextField();
        sitesComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 153));
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(null);

        jButton2.setBackground(new java.awt.Color(242, 242, 242));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(930, 400, 90, 30);

        jComboBox1.setBackground(new java.awt.Color(242, 242, 242));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Polirex", "Rubberon", "Poliresinas", "MGpolimeros", "ATRP" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox1);
        jComboBox1.setBounds(810, 400, 110, 30);

        jButton3.setBackground(new java.awt.Color(242, 242, 242));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(720, 400, 80, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        nomeLabelRu1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        nomeLabelRu1.setForeground(new java.awt.Color(7, 29, 73));
        jPanel1.add(nomeLabelRu1);
        nomeLabelRu1.setBounds(400, -10, 195, 80);

        areaLabelRu1.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        areaLabelRu1.setForeground(new java.awt.Color(7, 29, 73));
        jPanel1.add(areaLabelRu1);
        areaLabelRu1.setBounds(400, 20, 195, 70);

        siteLabelRU.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        siteLabelRU.setForeground(new java.awt.Color(7, 29, 73));
        jPanel1.add(siteLabelRU);
        siteLabelRU.setBounds(420, 130, 190, 60);

        zapLabelRU.setFont(new java.awt.Font("Century Schoolbook", 0, 10)); // NOI18N
        zapLabelRU.setForeground(new java.awt.Color(7, 29, 73));
        jPanel1.add(zapLabelRU);
        zapLabelRU.setBounds(420, 110, 200, 50);

        emailLabelRU.setFont(new java.awt.Font("Candara", 0, 11)); // NOI18N
        emailLabelRU.setForeground(new java.awt.Color(7, 29, 73));
        jPanel1.add(emailLabelRU);
        emailLabelRU.setBounds(420, 70, 200, 40);

        telefoneLabelRU.setFont(new java.awt.Font("Century Schoolbook", 0, 10)); // NOI18N
        telefoneLabelRU.setForeground(new java.awt.Color(7, 29, 73));
        jPanel1.add(telefoneLabelRU);
        telefoneLabelRU.setBounds(420, 90, 200, 40);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 670, 200);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(370, 90, 670, 180);

        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setName(""); // NOI18N
        jPanel4.add(jPanel3);
        jPanel3.setBounds(360, 80, 690, 10);
        jPanel4.add(jPanel5);
        jPanel5.setBounds(360, 90, 10, 190);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel6.setName(""); // NOI18N
        jPanel4.add(jPanel6);
        jPanel6.setBounds(370, 270, 680, 10);

        jPanel2.setBackground(new java.awt.Color(231, 231, 231));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Dados do Usuario");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 40, 160, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Area");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 200, 50, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Nome");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 90, 90, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Ramal");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 170, 90, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("E-mail");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 130, 100, 30);
        jPanel2.add(nomeTextField);
        nomeTextField.setBounds(70, 90, 156, 30);

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(emailTextField);
        emailTextField.setBounds(70, 130, 156, 30);
        jPanel2.add(ramalTextField);
        ramalTextField.setBounds(70, 170, 156, 30);

        areaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(areaTextField);
        areaTextField.setBounds(70, 210, 156, 30);

        Zap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Zap.setText("WhatsApp");
        jPanel2.add(Zap);
        Zap.setBounds(10, 240, 70, 50);

        try {
            zapFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        zapFormattedTextField.setToolTipText("");
        jPanel2.add(zapFormattedTextField);
        zapFormattedTextField.setBounds(80, 250, 140, 30);

        sitesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Polirex", "Rubberon", "Poliresinas", "MGpolimeros", "ATRP" }));
        jPanel2.add(sitesComboBox);
        sitesComboBox.setBounds(80, 290, 90, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Site");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 290, 37, 30);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(40, 50, 260, 380);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jPanel7);
        jPanel7.setBounds(1040, 90, 10, 190);
        jPanel4.add(jPanel9);
        jPanel9.setBounds(30, 40, 160, 150);

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jPanel8);
        jPanel8.setBounds(30, 40, 280, 400);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1130, 510);

        setBounds(0, 0, 1137, 513);
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void areaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaTextFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
            String nome = nomeTextField.getText();
            String email = emailTextField.getText();
            String ramal = ramalTextField.getText();
            String area = areaTextField.getText();
            String zap = zapFormattedTextField.getText();
            String site = (String) sitesComboBox.getSelectedItem();
            
            String msgError = "Digite Algo no campo para continuar";
            
        if (nomeTextField.getText().equalsIgnoreCase("") 
                || emailTextField.getText().equalsIgnoreCase("") 
                || ramalTextField.getText().equalsIgnoreCase("") 
                || areaTextField.getText().equalsIgnoreCase("")){
            
            JOptionPane.showMessageDialog(null, msgError, "ERRO", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(jComboBox1.getSelectedItem().equals("Rubberon")){
            ImageIcon imgRu = new ImageIcon(getClass().getResource("/Logos/Assinatra2.2.PNG"));
            jLabel1.setIcon(imgRu);
            
            if (sitesComboBox.getSelectedItem().equals("Rubberon")){
                     siteLabelRU.setText("    www.rubberon.com.br");
            }
            
            areaLabelRu1.setText(area);
            emailLabelRU.setText("     " + email + "@rubberon.com.br");
            nomeLabelRu1.setText(nome);

            if (zapFormattedTextField.getText().equals("(  )       -    ")){
                //telas.telefoneLabelRu5.setText(null);
                zapLabelRU.setText("    Sem Numero");
            }else{
                zapLabelRU.setText("    " + zap);
            }
            telefoneLabelRU.setText("    + 55 (11) 4344-1500 R." + ramal);
            
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDois().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Zap;
    public javax.swing.JLabel areaLabelRu1;
    public javax.swing.JTextField areaTextField;
    public javax.swing.JLabel emailLabelRU;
    public javax.swing.JTextField emailTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JLabel nomeLabelRu1;
    public javax.swing.JTextField nomeTextField;
    public javax.swing.JTextField ramalTextField;
    public javax.swing.JLabel siteLabelRU;
    private javax.swing.JComboBox<String> sitesComboBox;
    public javax.swing.JLabel telefoneLabelRU;
    public javax.swing.JFormattedTextField zapFormattedTextField;
    public javax.swing.JLabel zapLabelRU;
    // End of variables declaration//GEN-END:variables
}
