/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assinaturas;


import javax.swing.JOptionPane;

/**
 *
 * @author gustavo.lima
 */
public class telaAssinaturas extends javax.swing.JFrame {

    /**
     * Creates new form telaAssinaturas
     */
    public telaAssinaturas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        RamalTextField = new javax.swing.JTextField();
        areaTextField = new javax.swing.JTextField();
        Zap = new javax.swing.JLabel();
        DataDeNacimentoFormattedTextField = new javax.swing.JFormattedTextField();
        planoDeFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dados do Usuario");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 40, 160, 25);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 320, 80, 30);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(50, 320, 80, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Area");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 200, 50, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nome");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 90, 90, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ramal");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 170, 90, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E-mail");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 130, 100, 30);
        jPanel1.add(nomeTextField);
        nomeTextField.setBounds(70, 90, 156, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(70, 130, 156, 30);
        jPanel1.add(RamalTextField);
        RamalTextField.setBounds(70, 170, 156, 30);

        areaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(areaTextField);
        areaTextField.setBounds(70, 210, 156, 30);

        Zap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Zap.setForeground(new java.awt.Color(255, 255, 255));
        Zap.setText("WhatsApp");
        jPanel1.add(Zap);
        Zap.setBounds(10, 240, 70, 50);

        try {
            DataDeNacimentoFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DataDeNacimentoFormattedTextField.setToolTipText("");
        jPanel1.add(DataDeNacimentoFormattedTextField);
        DataDeNacimentoFormattedTextField.setBounds(80, 250, 140, 30);

        planoDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/plano de fundo.PNG"))); // NOI18N
        jPanel1.add(planoDeFundo);
        planoDeFundo.setBounds(0, -30, 280, 420);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 260, 380);

        jMenu1.setText("opções");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 274, 437);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaDois telas = new TelaDois();
        String erro = "Digite a informção no campo em branco";
        
        /*if (nomeTextField.getText().equals("")){
            JOptionPane.showInternalMessageDialog(null, erro);
        }*/

        /*//Rubberon
        telas.areaLabelRu.setText(area);
        telas.jLabel4.setText("    " + email + "@rubberon.com.br");
        telas.nomeLabelRu.setText(nome);
        
        if (DataDeNacimentoFormattedTextField.getText().equals("(  )       -    ")){
            //telas.telefoneLabelRu5.setText(null);
            telas.zapLabelRu.setText("    Sem Numero");
        }else{
            telas.zapLabelRu.setText("    " + zap);
        }
        telas.telefoneLabelRu5.setText("    + 55 (11) 4344-1500 R." + ramal);

        //Rubbron
        telas.areaLabelRu2.setText(" " + area);
        telas.emailLabelRu2.setText(" " + email + "@polirex.com.br");
        telas.nomeLabelRu2.setText(" " + nome);
        telas.telefoneLabelRu2.setText(" 4344-1500 Ramal:" + ramal);

        //Poleresinas
        telas.areaLabelRu3.setText(" " + area);
        telas.emailLabelRu3.setText(" " + email + "@poliresinas.com.br");
        telas.nomeLabelRu3.setText(" " + nome);
        telas.telefoneLabelRu3.setText(" Telefone: (11) 4344-1500 Ramal:" + ramal);

        //MG polimeros
        telas.areaLabelRu4.setText(" " + area);
        telas.emailLabelRu4.setText(" " + email + "@mgpolimero.com.br");
        telas.nomeLabelRu4.setText(" " + nome);
        telas.telefoneLabelRu4.setText(" Tel: +55 4344-150 Ramal:" + ramal);

        //Nortebag
        telas.areaLabelRu7.setText(" " + area);
        telas.emailLabelRu7.setText(" " + email + "@nortebag.com.br");
        telas.nomeLabelRu7.setText(" " + nome);
        telas.telefoneLabelRu7.setText(" + 55 11 4344-1500 Ramal:" + ramal);

        //atrp
        telas.areaLabelRu8.setText(" " + area);
        telas.emailLabelRu8.setText(" " + email + "@atrpservices.com.br");
        telas.nomeLabelRu8.setText(" " + nome);
        telas.telefoneLabelRu8.setText(" Office: +55 11 4344-1500 Ramal:" + ramal);

        telas.setVisible(true);
        this.setVisible(false);*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void areaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaTextFieldActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaAssinaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaAssinaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaAssinaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaAssinaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaAssinaturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JFormattedTextField DataDeNacimentoFormattedTextField;
    public javax.swing.JTextField RamalTextField;
    private javax.swing.JLabel Zap;
    public javax.swing.JTextField areaTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField nomeTextField;
    private javax.swing.JLabel planoDeFundo;
    // End of variables declaration//GEN-END:variables
}
